# Esercizio
1. Creare un dataframe che contenga i valori di iris
2. Creare due nuovi attributi che rappresentano l'area del petalo e del sepalo. Calcolare l'accuratezza con una divisione train /test 0.75/0.25 e un Decision Tree Classifier
3. Creare una discretizzazione dei valori in 4 bin (per ogni colonna del dataset), sostituire al dataset iniziale e calcolare l'accuratezza
4. Standardizzare il dataset del punto 2 e calcolare l'accuratezza con il classificatore di prima
5. Applicare il logaritmo (trasformazione custom) a tutte le colonne del dataset del punto 2 e calcolare l'accuratezza con il classificatore di prima
6. Creare una nuova colonna che abbia valore 1 se e solo se l'area del petalo e l'area del sepalo hanno entrambe valore superiore a 4 e calcolare l'accuratezza con il classificatore di prima

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn as sk
from sklearn import datasets

In [2]:
def accuracy(pred, result):
  return 1-(abs(pred-result)).sum()/len(result)

In [3]:
iris = datasets.load_iris()

In [4]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
X = iris.data
y = iris.target

In [7]:
df = pd.DataFrame(X, columns=iris['feature_names'])

In [8]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.25)

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [11]:
model = DecisionTreeClassifier()

In [12]:
model.fit(X_train, y_train)
result = model.predict(X_test)

In [13]:
accuracy(y_test, result)

1.0

In [14]:
accuracy(y_train, model.predict(X_train) )

1.0

## Creare due nuovi attributi che rappresentano l'area del petalo e del sepalo

In [16]:
df['areaSep'] = df['sepal length (cm)'] *df['sepal width (cm)']
df['areaPet'] = df['petal length (cm)'] *df['petal width (cm)']

In [17]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     areaSep  areaPet  
0      17.85     0.28  
1      14.70     0.28  
2      15.04     0.26  
3      14.26     0.30  
4      18.00     0.28  
..       ...      ...  
145    20.10    11.96  
146    15.75     9.50  
147    19.50    10.40  
148    21.08    12.42  
149    17.70     9.18  

[150 rows x 6 columns]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.25)

In [19]:
model.fit(X_train, y_train)
result = model.predict(X_test)
accuracy(y_test, result)

0.9736842105263158

In [20]:
accuracy(y_train, model.predict(X_train))

1.0

## Creare una discretizzazione dei valori in 4 bin

In [21]:
from sklearn import preprocessing

In [22]:
kb= preprocessing.KBinsDiscretizer(n_bins=4, encode='ordinal').fit(df)

In [23]:
kb.transform(df)

array([[1., 3., 0., 0., 2., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 2., 0.],
       [1., 3., 1., 1., 3., 1.],
       [0., 3., 0., 1., 0., 1.],
       [0., 3., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [1., 3., 0., 0., 2., 0.],
       [0., 3., 1., 0., 1., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [2., 3., 0., 0., 3., 0.],
       [1., 3., 0., 1., 3., 1.],
       [1., 3., 0., 1., 3., 1.],
       [1., 3., 0., 1., 2., 1.],
       [1., 3., 1., 1., 3., 1.],
       [1., 3., 0., 1., 2., 1.],
       [1., 3., 1., 0., 2., 0.],
       [1., 3., 0., 1., 2., 1.],
       [0., 3., 0., 0., 1., 0.],
       [1., 3., 1., 1., 1., 1.],
       [0., 3., 1., 0., 1., 0.],
       [0., 2., 1., 0., 0., 0.],
       [0., 3., 1., 1., 1., 1.],
       [1., 3., 0., 0., 2., 0.],
       [1., 3., 0., 0., 2., 0.],
       [0., 2., 1., 0., 0., 0.],
       [0.

In [24]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'areaSep', 'areaPet'],
      dtype='object')

In [25]:
dfd = pd.DataFrame(kb.transform(df), columns= df.columns)

In [26]:
dfd.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                1.0               3.0                0.0               0.0   
1                0.0               2.0                0.0               0.0   
2                0.0               2.0                0.0               0.0   
3                0.0               2.0                0.0               0.0   
4                0.0               3.0                0.0               0.0   

   areaSep  areaPet  
0      2.0      0.0  
1      0.0      0.0  
2      0.0      0.0  
3      0.0      0.0  
4      2.0      0.0

In [27]:
X_train, X_test, y_train, y_test = train_test_split(dfd, y, test_size=0.25)

In [28]:
model.fit(X_train, y_train)
result = model.predict(X_test)
accuracy(y_test, result)

0.8421052631578947

In [29]:
accuracy(y_train, model.predict(X_train))

0.9910714285714286

## Standardizzare il dataset del punto 2 e calcolare l'accuratezza con il classificatore di prima


In [30]:
sss= preprocessing.StandardScaler()

In [31]:
dfs = sss.fit(df)

In [32]:
dfs = pd.DataFrame(sss.transform(df), columns= df.columns)

In [33]:
dfs.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0          -0.900681          1.019004          -1.340227         -1.315444   
1          -1.143017         -0.131979          -1.340227         -1.315444   
2          -1.385353          0.328414          -1.397064         -1.315444   
3          -1.506521          0.098217          -1.283389         -1.315444   
4          -1.021849          1.249201          -1.340227         -1.315444   

    areaSep   areaPet  
0  0.008098 -1.174041  
1 -0.932024 -1.174041  
2 -0.830551 -1.178299  
3 -1.063343 -1.169783  
4  0.052866 -1.174041

In [34]:
X_train, X_test, y_train, y_test = train_test_split(dfs, y, test_size=0.25)

In [35]:
model.fit(X_train, y_train)
result = model.predict(X_test)
accuracy(y_test, result)

0.9210526315789473

In [36]:
accuracy(y_train, model.predict(X_train))

1.0

## Applicare il logaritmo (trasformazione custom) a tutte le colonne del dataset del punto 2 e calcolare l'accuratezza con il classificatore di prima


In [37]:
from sklearn.preprocessing import FunctionTransformer

transformer = FunctionTransformer(np.log)


In [38]:
dft = transformer.transform(df)

In [39]:
dft

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0             1.629241          1.252763           0.336472         -1.609438   
1             1.589235          1.098612           0.336472         -1.609438   
2             1.547563          1.163151           0.262364         -1.609438   
3             1.526056          1.131402           0.405465         -1.609438   
4             1.609438          1.280934           0.336472         -1.609438   
..                 ...               ...                ...               ...   
145           1.902108          1.098612           1.648659          0.832909   
146           1.840550          0.916291           1.609438          0.641854   
147           1.871802          1.098612           1.648659          0.693147   
148           1.824549          1.223775           1.686399          0.832909   
149           1.774952          1.098612           1.629241          0.587787   

      areaSep   areaPet  
0    2.882004 -1.272966  
1    2.687847 -1.272966  
2    2.710713 -1.347074  
3    2.657458 -1.203973  
4    2.890372 -1.272966  
..        ...       ...  
145  3.000720  2.481568  
146  2.756840  2.251292  
147  2.970414  2.341806  
148  3.048325  2.519308  
149  2.873565  2.217027  

[150 rows x 6 columns]

In [40]:
X_train, X_test, y_train, y_test = train_test_split(dft, y, test_size=0.25)

In [41]:
model.fit(X_train, y_train)
result = model.predict(X_test)
accuracy(y_test, result)

0.9473684210526316

In [42]:
accuracy(y_train, model.predict(X_train))

1.0

## Creare una nuova colonna che abbia valore 1 se e solo se l'area del petalo e l'area del sepalo hanno entrambe valore superiore a 4 e calcolare l'accuratezza con il classificatore di prima

In [43]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   areaSep  areaPet  
0    17.85     0.28  
1    14.70     0.28  
2    15.04     0.26  
3    14.26     0.30  
4    18.00     0.28

In [44]:
def checkArea(x,val=4):
  mask0 = x[:,0]>val
  mask1 = x[:,1]>val
  return mask0 & mask1


In [45]:
checkArea(X)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [46]:
transformer = FunctionTransformer(checkArea, validate=True)

In [47]:
boolArea = transformer.transform(df.loc[:,['areaSep','areaPet']].values)

In [48]:
boolArea

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [49]:
df["boolArea"] = boolArea

In [50]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   areaSep  areaPet  boolArea  
0    17.85     0.28     False  
1    14.70     0.28     False  
2    15.04     0.26     False  
3    14.26     0.30     False  
4    18.00     0.28     False

In [51]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     areaSep  areaPet  boolArea  
145    20.10    11.96      True  
146    15.75     9.50      True  
147    19.50    10.40      True  
148    21.08    12.42      True  
149    17.70     9.18      True

In [52]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.25)

In [53]:
model.fit(X_train, y_train)
result = model.predict(X_test)
accuracy(y_test, result)

0.9473684210526316

In [54]:
accuracy(y_train, model.predict(X_train))

1.0

In [57]:
y_test

array([0, 2, 2, 0, 2, 1, 2, 2, 0, 0, 0, 2, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 0, 2, 1])

In [58]:
result

array([0, 2, 2, 0, 2, 1, 2, 2, 0, 0, 0, 2, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 0, 1, 0, 2, 0, 2, 2, 0, 2, 1])